### ISSUE TITLE
The "Toggle Versioned Tables" doesn't actually do that

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#356]
When selecting "Toggle Versioned Tables", I would expect it to add/remove versioned tables - those that end with `_vN`. While most of them are removed, most of the unversioned tables are removed as well, e.g. `addon_aggregates`.

**Comment by washort** [comment]
I don't believe this was a change in behavior, but perhaps a change in data! Turns out that Angular's filtering feature looks at all strings in objects, no matter how deeply nested, so filtering out "_v" was filtering out tables that had columns like "app_version". I've fixed it to only filter on table name.

**Comment by madalincm** [comment]
I can still reproduce this issue in FF59(Win7) in STMO-stage

1. Go to https://pipeline-sql.stage.mozaws.net/queries/new
2. Select Athena as data source and use the toggle versioned switch

-- "normandy_stage.auto_json_log_normandy_admin_csp", " stmo.churn" and other tables that are not ending with "_v[x]" are removed

**Comment by madalincm** [comment]
Verified in FF59(Win7)
At this moment there aren't any versioned tables so using the switch has no effect. 
Giving this we can assume that the switch is no longer removing unversioned tables but I can't verify that versioned tables are removed correctly. I will be able to verify that only after the fix hits production.
